### ISSUE TITLE
請問能否新增對新版本 u3d 的支持

### ISSUE THREAD

**Issue by Zhen-Bo** [smalls0098/u3d-assets-tools#1]
如題,目前只有支援到 2017.4.17f1
想問下有沒有辦法支援到2021.3.9f1, 甚至更高的版本
看起來好像是`readFormatFS`的內容要更新?
不知道大老有沒有時間撥空更新, 或是有教學文可以讓我知道怎麼更新
萬分感謝

**Comment by smalls0098** [comment]
@Zhen-Bo 感谢您的关注，目前推荐您使用 https://github.com/K0lb3/UnityPy，这个项目。这个项目完善程度比较高

**Comment by Zhen-Bo** [comment]
@smalls0098 這個我有看過,不過好像沒法打包回u3d?
我看example裡面好像沒有存回u3d的方法只有存png的

**Comment by smalls0098** [comment]
@Zhen-Bo 可以打包，我用过写过打包。

**Comment by Zhen-Bo** [comment]
好的了解了,感謝OTz

**Comment by smalls0098** [comment]
unity-py load file后，可以直接操作assets，然后进行替换。可惜我代码已经封存，无法帮到你
